set_directive_loop_merge "rawdns/rawdns_row"
set_directive_loop_tripcount -max 8192 -avg 1920 "rawdns/rawdns_row"
set_directive_pipeline "rawdns/rawdns_col"
set_directive_loop_tripcount -avg 1080 "rawdns/rawdns_col"
#set_directive_unroll "rawdns/window_outer_loop"
#set_directive_unroll "rawdns/window_inter_loop"
#set_directive_unroll "rawdns/padding_outer_loop"
#set_directive_unroll "rawdns/padding_inter_loop"
#set_directive_unroll "rawdns/raw_read"
#set_directive_unroll "rawdns/additional_loop"
#set_directive_unroll "rawdns/lines_write"
#set_directive_array_partition rawdns nlm_lines
